
pipeline {
    agent any
    tools{
        maven 'maven_3_8_6'
        jdk 'JDK_1_8'
    }
    stages {
        // Giai đoạn dọn dẹp (Vì 1 Jenkins điều hành 1 công việc, đảm bảo môi trường sạch sẽ và nguyên sơ)
        stage("Clean Up") {
            steps {
                deleteDir()
            }
        }
        stage("Clone Repo") {
            steps {
                sh "git clone https://github.com/minhtv14/SpringBootHelloWord"
            }
        }
        stage("Build") {
            steps {
                dir("SpringBootHelloWord") {
                    sh "mvn clean install"
                }
            }
        }
        stage("Test") {
            steps {
                dir("SpringBootHelloWord") {
                    sh "mvn test"
                }
            }
        }
    }
}
