
pipeline {
    agent any
    tools{
        maven 'maven_3_8_6'
    }
    stages {
        stage("Clean Up") {
            steps {
                deleteDir()
            }
        }
        stage("Clone Repo") {
            steps {
                sh "git clone https://github.com/minhtv14/SpringBootHelloWord.git"
            }
        }
        stage("Build") {
            steps {
                dir("SpringBootHelloWord") {
                    sh "mvn clean install"
                }
            }
        }
        stage("Test") {
            steps {
                dir("SpringBootHelloWord") {
                    sh "mvn test"
                }
            }
        }
    }
}
